stages:
  - docker_image

build_docker:
  stage: docker_image
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/cdq:${cdq_version} .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/cdq:${cdq_version}
  tags:
    - executor:docker
  only:
    refs:
      - master
