stages:
  - docker_image

build_docker:
  stage: docker_image
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:$DOCKER_VERSION .
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE} 
  variables:
    DOCKER_VERSION: $(cat ${CI_COMMIT_TAG}| sed -En 's/([v0-9.]+)-.*/\1/p')
  tags:
    - executor:docker
  only:
    refs:
      - master
