stages:
  - docker_image

build_docker:
  stage: docker_image
  script:
    - export CURRENT_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
    - docker build -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:$CURRENT_VERSION .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE} 
  tags:
    - executor:docker
  only:
    refs:
      - master
