stages:
  - docker_image

build_docker:
  stage: docker_image
  before_script:
    - export DOCKER_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:$DOCKER_VERSION .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE} 
      #  variables:
      #DOCKER_VERSION: v1.0
  tags:
    - executor:docker
  only:
    refs:
      - master
